{{
    config(
        materialized='table'
    )
}}

WITH unioned as (
    {{ dbt_utils.union_relations(
        relations=[
            ref("clean_players"),
            ref("clean_depth_charts"),
            ref("clean_injuries"),
            ref("clean_pbp_participation"),
            ref("clean_play_by_play"),
            ref("clean_player_stats"),
            ref("clean_roster_weekly"),
            ref("clean_roster"),
            ref("clean_snap_counts"),
            ref("clean_player_stats")
        ],
        include=[
            "status",
            "display_name",
            "first_name",
            "last_name",
            "player_name",
            "esb_id",
            "player_key",
            "suffix",
            "birth_date",
            "college_name",
            "position_group",
            "position",
            "jersey_number",
            "height",
            "weight",
            "team_abbr",
            "team_seq",
            "current_team_id",
            "football_name",
            "entry_year",
            "rookie_year",
            "draft_club",
            "college_conference",
            "status_description_abbr",
            "status_short_description",
            "gsis_it_id",
            "short_name",
            "smart_id",
            "headshot",
            "draft_number",
            "uniform_number",
            "draft_round",
            "season",
            "full_name",
            "espn_id",
            "sportradar_id",
            "yahoo_id",
            "rotowire_id",
            "pff_id",
            "pfr_id",
            "fantasy_data_id",
            "sleeper_id"
        ]
    ) }}
),

deduplicated as (
    SELECT
    player_key,
    array_agg(esb_id) FILTER (WHERE esb_id is not null)[1] as esb_id,
    array_agg(espn_id) FILTER (WHERE espn_id is not null)[1] as espn_id,
    array_agg(fantasy_data_id) FILTER (WHERE fantasy_data_id is not null)[1] as fantasy_data_id,
    array_agg(gsis_it_id) FILTER (WHERE gsis_it_id is not null)[1] as gsis_it_id,
    array_agg(pff_id) FILTER (WHERE pff_id is not null)[1] as pff_id,
    array_agg(pfr_id) FILTER (WHERE pfr_id is not null)[1] as pfr_id,
    array_agg(rotowire_id) FILTER (WHERE rotowire_id is not null)[1] as rotowire_id,
    array_agg(sleeper_id) FILTER (WHERE sleeper_id is not null)[1] as sleeper_id,
    array_agg(sportradar_id) FILTER (WHERE sportradar_id is not null)[1] as sportradar_id,
    array_agg(yahoo_id) FILTER (WHERE yahoo_id is not null)[1] as yahoo_id,
    array_agg(first_name) FILTER (WHERE first_name is not null)[1] as first_name,
    array_agg(last_name) FILTER (WHERE last_name is not null)[1] as last_name,
    array_agg(full_name) FILTER (WHERE full_name is not null)[1] as full_name,
    array_agg(player_name) FILTER (WHERE player_name is not null)[1] as player_name,
    array_agg(display_name) FILTER (WHERE display_name is not null)[1] as display_name,
    array_agg(status) FILTER (WHERE status is not null)[1] as status,
    array_agg(position_group) FILTER (WHERE position_group is not null)[1] as position_group,
    array_agg(position) FILTER (WHERE position is not null)[1] as position,
    array_agg(suffix) FILTER (WHERE suffix is not null)[1] as suffix,
    array_agg(birth_date) FILTER (WHERE birth_date is not null)[1] as birth_date,
    array_agg(college_name) FILTER (WHERE college_name is not null)[1] as college_name,
    array_agg(jersey_number) FILTER (WHERE jersey_number is not null)[1] as jersey_number,
    array_agg(height) FILTER (WHERE height is not null)[1] as height,
    array_agg(weight) FILTER (WHERE weight is not null)[1] as weight,
    array_agg(team_abbr) FILTER (WHERE team_abbr is not null)[1] as team_abbr,
    array_agg(team_seq) FILTER (WHERE team_seq is not null)[1] as team_seq,
    array_agg(current_team_id) FILTER (WHERE current_team_id is not null)[1] as current_team_id,
    array_agg(football_name) FILTER (WHERE football_name is not null)[1] as football_name,
    array_agg(entry_year) FILTER (WHERE entry_year is not null)[1] as entry_year,
    array_agg(rookie_year) FILTER (WHERE rookie_year is not null)[1] as rookie_year,
    array_agg(draft_club) FILTER (WHERE draft_club is not null)[1] as draft_club,
    array_agg(college_conference) FILTER (WHERE college_conference is not null)[1] as college_conference,
    array_agg(status_description_abbr) FILTER (WHERE status_description_abbr is not null)[1] as status_description_abbr,
    array_agg(status_short_description) FILTER (WHERE status_short_description is not null)[1] as status_short_description,
    array_agg(short_name) FILTER (WHERE short_name is not null)[1] as short_name,
    array_agg(smart_id) FILTER (WHERE smart_id is not null)[1] as smart_id,
    array_agg(headshot) FILTER (WHERE headshot is not null)[1] as headshot,
    array_agg(draft_number) FILTER (WHERE draft_number is not null)[1] as draft_number,
    array_agg(uniform_number) FILTER (WHERE uniform_number is not null)[1] as uniform_number,
    array_agg(draft_round) FILTER (WHERE draft_round is not null)[1] as draft_round,
    array_agg(season) FILTER (WHERE season is not null)[1] as season
    FROM unioned
    WHERE player_key is not null
    GROUP BY 1
)

SELECT
    player_key,
    esb_id,
    espn_id,
    fantasy_data_id,
    gsis_it_id,
    pff_id,
    pfr_id,
    rotowire_id,
    sleeper_id,
    sportradar_id,
    yahoo_id,
    first_name,
    last_name,
    full_name,
    display_name,
    player_name,
    status,
    position_group,
    position,
    suffix,
    birth_date,
    college_name,
    jersey_number,
    height,
    weight,
    team_abbr,
    team_seq,
    current_team_id,
    football_name,
    entry_year,
    rookie_year,
    draft_club,
    college_conference,
    status_description_abbr,
    status_short_description,
    short_name,
    smart_id,
    headshot,
    draft_number,
    uniform_number,
    draft_round,
    season
FROM deduplicated
