{{
    config(
        materialized='table'
    )
}}

WITH source AS (
    SELECT * FROM {{ ref('clean_play_by_play') }}
)

SELECT
    {{ dbt_utils.generate_surrogate_key(['play_id']) }} AS play_id,
    {{ dbt_utils.generate_surrogate_key(['game_id']) }} AS game_id,
    home_team,
    away_team,
    season_type,
    week,
    game_date,
    time,
    quarter,
    description,

    -- foreign keys

    {{ dbt_utils.generate_surrogate_key(['player_key_blocked']) }} AS player_id_blocked,
    {{ dbt_utils.generate_surrogate_key(['player_key_fumbled']) }} AS player_id_fumbled,
    {{ dbt_utils.generate_surrogate_key(['player_key_half_sack_1']) }} AS player_id_half_sack_1,
    {{ dbt_utils.generate_surrogate_key(['player_key_half_sack_2']) }} AS player_id_half_sack_2,
    {{ dbt_utils.generate_surrogate_key(['player_key_interception']) }} AS player_id_interception,
    {{ dbt_utils.generate_surrogate_key(['player_key_kicker']) }} AS player_id_kicker,
    {{ dbt_utils.generate_surrogate_key(['player_key_kickoff_returner']) }} AS player_id_kickoff_returner,
    {{ dbt_utils.generate_surrogate_key(['player_key_lateral_interception']) }} AS player_id_lateral_interception,
    {{ dbt_utils.generate_surrogate_key(['player_key_lateral_kickoff_returner']) }} AS player_id_lateral_kickoff_returner,
    {{ dbt_utils.generate_surrogate_key(['player_key_lateral_punt_returner']) }} AS player_id_lateral_punt_returner,
    {{ dbt_utils.generate_surrogate_key(['player_key_lateral_receiver']) }} AS player_id_lateral_receiver,
    {{ dbt_utils.generate_surrogate_key(['player_key_lateral_rusher']) }} AS player_id_lateral_rusher,
    {{ dbt_utils.generate_surrogate_key(['player_key_lateral_sack']) }} AS player_id_lateral_sack,
    {{ dbt_utils.generate_surrogate_key(['player_key_passer']) }} AS player_id_passer,
    {{ dbt_utils.generate_surrogate_key(['player_key_penalty']) }} AS player_id_penalty,
    {{ dbt_utils.generate_surrogate_key(['player_key_punt_returner']) }} AS player_id_punt_returner,
    {{ dbt_utils.generate_surrogate_key(['player_key_punter']) }} AS player_id_punter,
    {{ dbt_utils.generate_surrogate_key(['player_key_receiver']) }} AS player_id_receiver,
    {{ dbt_utils.generate_surrogate_key(['player_key_rusher']) }} AS player_id_rusher,
    {{ dbt_utils.generate_surrogate_key(['player_key_sack']) }} AS player_id_sack,
    {{ dbt_utils.generate_surrogate_key(['player_key_safety']) }} AS player_id_safety,
    {{ dbt_utils.generate_surrogate_key(['player_key_touchdown']) }} AS player_id_touchdown,

    -- play info

    st_play_type,
    penalty_type,
    play_clock,
    play_deleted,
    play_type_nfl,
    pass_location,
    run_location,
    run_gap,
    play_type,
    down,
    yard_line,
    field_goal_result,
    kick_distance,
    extra_point_result,
    two_point_conv_result,
    td_team,
    penalty_team,

    -- drive info

    fixed_drive_result,
    series_result,

    -- game info

    away_score,
    home_score,
    location,
    result,
    total,
    spread_line,
    total_line,
    div_game,
    roof,
    surface,
    temp,
    wind,
    home_coach,
    away_coach,
    start_time,
    time_of_day,
    stadium,
    weather,
    total_home_score,
    total_away_score,
    posteam_score,
    defteam_score,

    -- logical info

    possessing_team,
    possessing_team_type,
    defending_team,
    pass_length_description,

    -- binary facts

    aborted_play,
    drive_ended_with_score,
    first_down,
    lateral_reception,
    lateral_recovery,
    lateral_return,
    lateral_rush,
    pass,
    play,
    rush,
    special,
    success,
    qb_hit,
    rush_attempt,
    pass_attempt,
    sack,
    touchdown,
    pass_touchdown,
    rush_touchdown,
    return_touchdown,
    extra_point_attempt,
    two_point_attempt,
    field_goal_attempt,
    kickoff_attempt,
    punt_attempt,
    fumble,
    complete_pass,
    shotgun,
    no_huddle,
    qb_dropback,
    qb_kneel,
    qb_spike,
    qb_scramble,
    special_teams_play,
    punt_blocked,
    first_down_rush,
    first_down_pass,
    first_down_penalty,
    third_down_converted,
    third_down_failed,
    fourth_down_converted,
    fourth_down_failed,
    incomplete_pass,
    touchback,
    interception,
    punt_inside_twenty,
    punt_in_endzone,
    punt_out_of_bounds,
    punt_downed,
    punt_fair_catch,
    kickoff_inside_twenty,
    kickoff_in_endzone,
    kickoff_out_of_bounds,
    kickoff_downed,
    kickoff_fair_catch,
    fumble_forced,
    fumble_not_forced,
    fumble_out_of_bounds,
    solo_tackle,
    safety,
    penalty,
    tackled_for_loss,
    fumble_lost,
    own_kickoff_recovery,
    own_kickoff_recovery_td,
    drive_inside20,
    goal_line_play,

    -- yardage facts

    air_yards,
    drive_yards_penalized,
    fumble_recovery_1_yards,
    fumble_recovery_2_yards,
    lateral_receiving_yards,
    lateral_rushing_yards,
    net_yards,
    passing_yards,
    penalty_yards,
    receiving_yards,
    return_yards,
    rushing_yards,
    yards_after_catch,
    yards_gained,
    yards_to_go,

    -- drive facts
    drive_play_count,
    drive_time_of_possession,
    drive_first_downs,
FROM source

